### ISSUE TITLE
ref.zip file is corrupted

### ISSUE THREAD

**Issue by ghost** [GreyGuoweiChen/VirBot#15]
I tried to unzip the ref.zip file but it did not work. Running `zip -T` showed the following output:

zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (ref.zip)

Meaning it is corrupted

**Comment by GreyGuoweiChen** [comment]
Hello,

Thanks for you attentions. I downloaded and double checked its validity. And it works fine to me.

I just uploaded a md5 file for "ref.zip". You may check the completeness of the file by md5sum now.

Thanks

**Comment by ghost** [comment]
Thanks. I also tried to download the OneDrive file and it worked for me.
